
package edu.memphis.ehands;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeterminantCalcService", targetNamespace = "http://ehands.memphis.edu/", wsdlLocation = "http://localhost:8080/services/DeterminantCalc?wsdl")
public class DeterminantCalcService
    extends Service
{

    private final static URL DETERMINANTCALCSERVICE_WSDL_LOCATION;
    private final static WebServiceException DETERMINANTCALCSERVICE_EXCEPTION;
    private final static QName DETERMINANTCALCSERVICE_QNAME = new QName("http://ehands.memphis.edu/", "DeterminantCalcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/DeterminantCalc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETERMINANTCALCSERVICE_WSDL_LOCATION = url;
        DETERMINANTCALCSERVICE_EXCEPTION = e;
    }

    public DeterminantCalcService() {
        super(__getWsdlLocation(), DETERMINANTCALCSERVICE_QNAME);
    }


    public DeterminantCalcService(URL wsdlLocation) {
        super(wsdlLocation, DETERMINANTCALCSERVICE_QNAME);
    }


    public DeterminantCalcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns DeterminantCalc
     */
    @WebEndpoint(name = "DeterminantCalcPort")
    public DeterminantCalc getDeterminantCalcPort() {
        return super.getPort(new QName("http://ehands.memphis.edu/", "DeterminantCalcPort"), DeterminantCalc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeterminantCalc
     */
    @WebEndpoint(name = "DeterminantCalcPort")
    public DeterminantCalc getDeterminantCalcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ehands.memphis.edu/", "DeterminantCalcPort"), DeterminantCalc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETERMINANTCALCSERVICE_EXCEPTION!= null) {
            throw DETERMINANTCALCSERVICE_EXCEPTION;
        }
        return DETERMINANTCALCSERVICE_WSDL_LOCATION;
    }

}
