
package edu.memphis.ehands;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LUDecomposerService", targetNamespace = "http://ehands.memphis.edu/", wsdlLocation = "http://localhost:8080/services/LUDecomposer?wsdl")
public class LUDecomposerService
    extends Service
{

    private final static URL LUDECOMPOSERSERVICE_WSDL_LOCATION;
    private final static WebServiceException LUDECOMPOSERSERVICE_EXCEPTION;
    private final static QName LUDECOMPOSERSERVICE_QNAME = new QName("http://ehands.memphis.edu/", "LUDecomposerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/LUDecomposer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LUDECOMPOSERSERVICE_WSDL_LOCATION = url;
        LUDECOMPOSERSERVICE_EXCEPTION = e;
    }

    public LUDecomposerService() {
        super(__getWsdlLocation(), LUDECOMPOSERSERVICE_QNAME);
    }


    public LUDecomposerService(URL wsdlLocation) {
        super(wsdlLocation, LUDECOMPOSERSERVICE_QNAME);
    }


    public LUDecomposerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns LUDecomposer
     */
    @WebEndpoint(name = "LUDecomposerPort")
    public LUDecomposer getLUDecomposerPort() {
        return super.getPort(new QName("http://ehands.memphis.edu/", "LUDecomposerPort"), LUDecomposer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LUDecomposer
     */
    @WebEndpoint(name = "LUDecomposerPort")
    public LUDecomposer getLUDecomposerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ehands.memphis.edu/", "LUDecomposerPort"), LUDecomposer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LUDECOMPOSERSERVICE_EXCEPTION!= null) {
            throw LUDECOMPOSERSERVICE_EXCEPTION;
        }
        return LUDECOMPOSERSERVICE_WSDL_LOCATION;
    }

}
