
package edu.memphis.ehands;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LUDecomposer", targetNamespace = "http://ehands.memphis.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LUDecomposer {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.memphis.ehands.DecomposedMatrix
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decompose", targetNamespace = "http://ehands.memphis.edu/", className = "edu.memphis.ehands.Decompose")
    @ResponseWrapper(localName = "decomposeResponse", targetNamespace = "http://ehands.memphis.edu/", className = "edu.memphis.ehands.DecomposeResponse")
    @Action(input = "http://ehands.memphis.edu/LUDecomposer/decomposeRequest", output = "http://ehands.memphis.edu/LUDecomposer/decomposeResponse")
    public DecomposedMatrix decompose(
        @WebParam(name = "arg0", targetNamespace = "")
        Matrix arg0);

}
