
package edu.memphis.ehands;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SquareMatrixValidatorService", targetNamespace = "http://ehands.memphis.edu/", wsdlLocation = "http://localhost:8080/services/SquareMatrixValidator?wsdl")
public class SquareMatrixValidatorService
    extends Service
{

    private final static URL SQUAREMATRIXVALIDATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SQUAREMATRIXVALIDATORSERVICE_EXCEPTION;
    private final static QName SQUAREMATRIXVALIDATORSERVICE_QNAME = new QName("http://ehands.memphis.edu/", "SquareMatrixValidatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/SquareMatrixValidator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SQUAREMATRIXVALIDATORSERVICE_WSDL_LOCATION = url;
        SQUAREMATRIXVALIDATORSERVICE_EXCEPTION = e;
    }

    public SquareMatrixValidatorService() {
        super(__getWsdlLocation(), SQUAREMATRIXVALIDATORSERVICE_QNAME);
    }

    public SquareMatrixValidatorService(URL wsdlLocation) {
        super(wsdlLocation, SQUAREMATRIXVALIDATORSERVICE_QNAME);
    }

    public SquareMatrixValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SquareMatrixValidator
     */
    @WebEndpoint(name = "SquareMatrixValidatorPort")
    public SquareMatrixValidator getSquareMatrixValidatorPort() {
        return super.getPort(new QName("http://ehands.memphis.edu/", "SquareMatrixValidatorPort"), SquareMatrixValidator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SquareMatrixValidator
     */
    @WebEndpoint(name = "SquareMatrixValidatorPort")
    public SquareMatrixValidator getSquareMatrixValidatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ehands.memphis.edu/", "SquareMatrixValidatorPort"), SquareMatrixValidator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SQUAREMATRIXVALIDATORSERVICE_EXCEPTION!= null) {
            throw SQUAREMATRIXVALIDATORSERVICE_EXCEPTION;
        }
        return SQUAREMATRIXVALIDATORSERVICE_WSDL_LOCATION;
    }

}
